---
apiVersion: v1
kind: Service
metadata:
  name: test-app
  namespace: k8s
  labels: 
    app: test-app
spec:
  selector:
    app: test-app
    #tier: frontend
  type: NodePort
  ports:
    - port: 8080               #container port
      targetPort: 8080           #Pod port
      #nodePort: 31802     #If type is NodePort then use nodePort   
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  namespace: k8s
  labels: 
    app: test-app   
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: test-app
      #tier: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template: 
    metadata: 
      labels: 
        app: test-app
        #tier: frontend
      name: test-app
    spec:
      containers: 
        - image: lalchandrajak05/myapp
          name: test-app
          imagePullPolicy: Always
          ##env:
          #- name: SPRING_PROFILES_ACTIVE
          #  value: "10.210.0.133"
